server:
  port: 8082
spring:
  application:
    name: product
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/db_name
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

# for eureka service (service registry and discovery)
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/

