server:
  port: 8082
spring:
  application:
    name: product
  profiles:
    active: dev
  # config server(8888 is the port of config server)
  config:
    import: "configserver:https://localhost:8888"
# for eureka service (service registry and discovery)
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/

