business:
  info: "This is business production"

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/db_name
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver