business:
  info: "This is identity development"
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/oauth2_db 
      database: oauth2_db                      
      username: sokkhann                   
      password: 1234 