product:
  info: "This is product QA"
  
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/service_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver