server:
  port: 8761
spring:
  application:
    name: eureka-server
#disable for eureka server register itself
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
