spring:
  application:
    name: config-server
  profiles:
    active: git # it can be native, git, and vault
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sokkhann/configuration-managements.git
          default-label: main
          search-paths: '/yelp-config/**' #this is for search paths
server:
  port: 8888